version: '3.8'

services:

  backend:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/interview
    depends_on:
      - db

  db:
    image: postgres:16.1
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=interview
